config/routes.rb
EbV3::Application.routes.draw do

    root 'static_pages#index'
    mount Resque::Server, :at => "/resque"
    get   "/invitations" => "invitations#index"
    get   "/accounts" => "accounts#index"

    get   "/apply" => "invitations#new"
    post  "/apply" => "invitations#create"
    get   "/welcome/:invitation_token" => "invitations#welcome", as: :welcome
    post  "/validate/:invitation_token" => "invitations#validate"

    get   "/login" => "accounts#login", as: :login
    get   "/signup" => "accounts#signup", as: :signup
    post  "/signup" => "accounts#create", as: :create_account

    get   "/processing/:account_token" => "accounts#processing", as: :processing
    get   "/checkstatus/:account_token" => "accounts#check_status"

    get "/auth/:provider/callback" => "authentications#create"
    
    get "/signup_callback" => "authentications#create_account_from_eb", as: :signup_callback

end

app/models/invitation.rb
class Invitation < ActiveRecord::Base
	belongs_to :authentication


	validate :has_valid_email?
	validate :not_on_waiting_list

#	validates :name,
#				presence: true

	before_save :downcase_email
	before_create :generate_token
	after_create :send_email


	def validate!
		self.validated_at = Time.now
		self.save
	end


	def validated?
		!self.validated_at.blank?
	end

	def to_param
		self.token
	end


	private
	def has_valid_email?
		unless !self.email.blank? and self.email.is_valid_email?
			errors.add :email, "is not a valid email"
		end
	end


	def not_on_waiting_list
		inv = Invitation.find_by_email(email)
		if inv
			errors.add :email, 'is already on the waiting list'
		end
	end


	def generate_token
		self.token = Digest::SHA1.hexdigest([Time.now, rand].join)
	end


	def downcase_email
		self.email = self.email.downcase
	end


	def send_email
      InvitationMailer.welcome_email(self.id).deliver
	end

end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  http_basic_authenticate_with name: APP_CONFIG['admin_username'], password: APP_CONFIG['admin_pwd'], only: ["index"]
  include ApplicationHelper

  def new
    @invitation ||= Invitation.new
  end


  def create
    @invitation = Invitation.find_by_email(invitation_params[:email]) || Invitation.new(invitation_params)

    if @invitation.new_record?
      if @invitation.save
        respond_to do |format|
#          format.html { redirect_to "/hi/welcome/#{@invitation.token}" }
          format.html { redirect_to eb_path(welcome_path(@invitation)) }
          format.js   { render :js => "window.location = '#{eb_path(welcome_path(@invitation))}'" }
        end
      else
        respond_to do |format|
          format.html { render action: :new }
          format.js   { render partial: "shared/error_messages", status: :unprocessable_entity, content_type: 'text/html', locals: {target: @invitation} }
        end
      end
    else
      # this email is already on the waiting list,
      # redirect directly to invitation welcome page
      respond_to do |format|
#        format.html { redirect_to "/hi/welcome/#{@invitation.token}"  }
        format.html { redirect_to eb_path(welcome_path(@invitation))  }
        format.js   { render :js => "window.location = '#{eb_path(welcome_path(@invitation))}'" }
      end
    end
  end


  def welcome
    @invitation ||= Invitation.find_by(token: params[:invitation_token])
  end


  def edit
    @invitation ||= Invitation.find_by(token: params[:invitation_token])
  end


  def destroy
    @invitation ||= Invitation.find_by(token: params[:invitation_token])
  end


  def index
    @invitations = Invitation.paginate(:page => params[:page])
  end


  def validate
    @invitation = Invitation.find_by(token: params[:invitation_token])
    if @invitation.validate!
      respond_to do |format|
        format.html { redirect_to welcome_path(@invitation) }
      end
    else
      respond_to do |format|
        format.html { redirect_to index }
      end
    end
  end


  private
  def invitation_params
    params.require(:invitation).permit(:name, :email, :company, :promocode)
  end
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/views/invitations/_form.haml
%script
  mixpanel.track("Invitation Request Form Rendered")
%h4.text-center{:style => "margin-top: 40px"} Request early beta access


= form_for @invitation, url: eb_path(apply_path), method: :post, html: {id: "invitation-request"} do |f|
  - if @invitation.errors.any?
    #error_explanation.alert.alert-danger
      %button.close{'type' => 'button', 'data-dismiss' => 'alert', href: '#', 'aria-hidden' => 'true'} x
      %h4= "#{pluralize(@invitation.errors.count, "error")} prohibited this invitation for being saved:"
      %ul
        - @invitation.errors.full_messages.each do |msg|
          %li.h5= msg


  .form-group
    = f.text_field :name, placeholder: "Name", class: "form-control"

  .form-group
    = f.text_field :email, placeholder: "Email", class: "form-control"

  .form-group
    = f.text_field :company, placeholder: "Company Name", class: "form-control"

  .form-group
    = f.submit 'Request Invitation', class: "btn btn-block btn-warning", id: "request"

  .h5.text-center
    %a.toggle_form Use Github

app/views/invitations/_jumbotron.haml
.jumbotron.eb-header#jumbotron
  .container
    .row
      .col-md-12.github
        .col-md-12.sign-up-copy.text-center
          %h1.header-text Deploy code in one click. Any stack. Any cloud.
          %h3.sub-header
            For developers, teams, and enterprise. Rapid deployment. Freedom from infrastructure.

    .row
      .col-md-6.col-md-offset-3.text-center#christmas-signup
        =form_for @invitation, url: eb_path(apply_path), method: :post, remote: true, html: {class: "form-inline skinny", role: "form"} do |f|
          #error_messages
          .form-group
            = f.text_field :email, placeholder: "Enter work email", class: "form-control input-lg", :track => "Email Inline"

          .form-group
            = f.submit 'Get Invitation', class: "btn signup", :track => "Request Inline"

        %h5.text-center#git-omniauth
          = link_to "<i class='fa fa-github'></i> Request with GitHub".html_safe, omniauth_signin_path('github'), :class => "text-center", :id => "github", :track => "GitHub Inline"

            
    .row
      .col-md-12.text-center
        =image_tag "dots.png", class: 'dots'
        .col-md-4.providers
          =image_tag "step1.png"
          %h4.round
            1
          %h5
            Add Your Clouds
        .col-md-4.stack
          =image_tag "step2.png"
          %h4.round
            2
          %h5
            Customize Your Stack
        .col-md-4
          =image_tag "step3.png"
          %h4.round
            3
          %h5
            Deploy Your Code

app/views/invitations/_share_twitter.html.erb
<a href="https://twitter.com/share" class="twitter-share-button" data-size="large" data-text="Request invite for the ElasticBox Developer Platform. Beta launch coming soon!" data-via="ElasticBox"><i class="icon-twitter"></i> Share On Twitter</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>



<a href="https://twitter.com/share?url=original_referer=http%3A%2F%2Flocalhost%3A3000%2Fwelcome%2F05392bb0828e2888411324bb0c7a5168aa80233b&text=Request%20invite%20for%20the%20ElasticBox%20Developer%20Platform.%20Beta%20launch%20coming%20soon!&tw_p=tweetbutton&url=http%3A%2F%2Flocalhost%3A3000%2Fwelcome%2F05392bb0828e2888411324bb0c7a5168aa80233b&via=ElasticBox" target="_blank"

<a href="http://twitter.com/share?url=http%3A%2F%2Fbeta.elasticbox.com%2Fpages%2Ftweet-button&text=Sign%20up%20for%20the%20ElasticBox%20Developer%20Platform.%20Beta%20launch%20coming%20soon!" target="_blank">

app/views/invitations/edit.html.erb
<h1>Invitations#edit</h1>
<p>Find me in app/views/invitations/edit.html.erb</p>

<%= render partial: "invitations/form" %>

app/views/invitations/index.haml
.container
  %h1{:style => "margin-top: 100px"} Invitations
  %table.table.table-striped
    %thead
      %tr
        %th Name
        %th Email
        %th Created At
        %th Validated?


    %tbody
      - @invitations.each do |i|
        %tr
          %th= i.name
          %th= i.email
          %th= i.created_at
          %th= i.validated?

    = will_paginate @invitations

app/views/invitations/new.haml
.jumbotron.eb-header#jumbotron{style:"min-height:480px;"}
  .container
    .row
      .col-md-12.sign-up-form.github{style:"display:none;"}
        .col-md-11.col-md-offset-1.sign-up-copy.text-center
          %h1.header-text Deploy apps in one click. Any stack. Any host.
          %h3.sub-header
            For developers, teams, and enterprise. Rapid deployment. Freedom from infrastructure.

        .col-md-6.col-md-offset-3
          %h4.text-center Coming early 2014, request early beta access
          = link_to "<i class='icon-github'></i> Request with Github".html_safe, '/auth/github', :class => "btn btn-lg btn-block btn-success text-center signup"
          %h5.text-center
            %a#email-signup.toggle_form Use email

      .col-md-6.col-md-offset-3.sign-up-form.email{style:"display:inline;"}
        =render partial:"invitations/form"




= render partial: "static_pages/mktg_copy_home"

app/views/invitations/welcome.haml
%script
  mixpanel.track("Welcome View Rendered")

.jumbotron{style:"min-height:510px;"}
  .container
    .row
      .col-md-6.col-md-offset-3.well
        %h2.welcome.text-center Congratulations, you are ##{@invitation.id}!

        %hr.soften
        %h4.text-center{ style: "line-height:1.5em;"}
          Check your email to confirm your account. If you have a spare moment, please take our #{ link_to 'developer survey', 'https://docs.google.com/a/elasticbox.com/forms/d/1nLae_8N9iJAyFznmMnt5H95TvJZvDmRG0UYr7V12IZ8/viewform', :class => 'welcome'} which will help us build the product you want to use.
        %hr.soften
        .beta-share.text-center
          .col-md-6
            .btn.btn-md.col-md-12.btn-info#linkedin{track: "LinkedIn Share Clicked"}
              =fa_icon "linkedin"
              Share On LinkedIn
          .col-md-6
            .btn.btn-md.col-md-12.btn-info#twitter{track: "Twitter Share Clicked"}
              =fa_icon "twitter"
              Share On Twitter

= render "static_pages/mktg_copy_home"