config/routes.rb
EbV3::Application.routes.draw do

    root 'static_pages#index'
    mount Resque::Server, :at => "/resque"
    get   "/invitations" => "invitations#index"
    get   "/accounts" => "accounts#index"

    get   "/apply" => "invitations#new"
    post  "/apply" => "invitations#create"
    get   "/welcome/:invitation_token" => "invitations#welcome", as: :welcome
    post  "/validate/:invitation_token" => "invitations#validate"

    get   "/login" => "accounts#login", as: :login
    get   "/signup" => "accounts#signup", as: :signup
    post  "/signup" => "accounts#create", as: :create_account

    get   "/processing/:account_token" => "accounts#processing", as: :processing
    get   "/checkstatus/:account_token" => "accounts#check_status"

    get "/auth/:provider/callback" => "authentications#create"
    
    get "/signup_callback" => "authentications#create_account_from_eb", as: :signup_callback

end

app/models/account.rb
# http://girders.org/blog/2011/10/30/how-queuing-with-resque-works/

class Account < ActiveRecord::Base
	require 'digest/sha1'

	include EBAPI

	has_one :authentication,
				dependent: :destroy


	validate :has_valid_email?

	validates :email,
				presence: true,
				uniqueness: true

	validates :eb_tenant_name,
				uniqueness: true,
				unless: Proc.new { |a| a.eb_tenant_name.blank? }

	# password is required, unless the account is created via authentication.
	# (in which case we pass does_not_require_password = true)
#	validates :password,
#				presence: true,
#				unless: :does_not_require_password
#
	validates :name,
				presence: true

	before_save :set_email_and_encrypt_password
	before_create :generate_token#_and_calculate_name
	after_create :enqueue_tenant_creation


	attr_accessor :password, :does_not_require_password


	def to_param
		self.token
	end


	def create_tenant(options={})
		self.calculate_tenant_name!
		self.password = options.try(:[], "password")

		payload = self.eb_json

		response = EBAPI::create_tenant(payload)

	    case response
	    when Net::HTTPSuccess
	    	begin
		    	self.eb_cookie = JSON(response.body)["cookie"]
		    	self.eb_tenant_id = JSON(response.body)["id"]
		    	self.does_not_require_password = true
		    	self.save

		    rescue ActiveRecord::RecordNotSaved => e
		    	logger.error self.errors.full_messages

		    	self.error_creating_tenant!
		    	false
		    end
	    else
	    	#how do we communicate an error?
	    	self.error_creating_tenant!
	    	false
	    end
	end



	def check_tenant_status

		logger.debug ">>>>>>> CHECK TENANT STATUS >>>> #{self.eb_tenant_id.blank?}"

		case self.eb_tenant_id
		when blank? || nil
			'processing'

		when "error"
			"error"

		else
			response = EBAPI::tenant_status(self.eb_tenant_id)

		    case response
		    when Net::HTTPSuccess
		    	#tenant is started, need to check status for ready
		    	logger.debug "SUCCESS!"
		    	logger.debug response.body.inspect

		    	status = JSON(response.body)['status']
		    	status
		    else
		    	#how do we communicate an error?
		    	logger.debug "ERROR :'("
		    	logger.debug response.body.inspect

		    	false
		    end
		end

	end



	def destroy_tenant
		logger.debug ">>>>>>> CHECK TENANT STATUS >>>> #{self.eb_tenant_id}"

    	response = EBAPI::destroy_tenant(self.eb_tenant_id)

	    case response
	    when Net::HTTPSuccess
	    	self.eb_tenant_id = ""
	    	self.eb_tenant_name = ""
	    	self.does_not_require_password = true
	    	self.save!
	    end
	end



	def eb_json
    	user_json = {
    		"name"  => self.eb_tenant_name, 
    		"owner" => {
    			"password" => self.password || "", # password is only passed at signup via email
    			"first_name" => self.first_name,
    			"last_name" => self.last_name,
    			"email" => self.email
    		}
    	}

    	if self.authentication
    		github_json = {
    			"username" => self.authentication.try(:github_username),
    			"id" => self.authentication.try(:github_uid)
    		}

    		icon_json = self.authentication.try(:github_image)

    		user_json["owner"]["github"] = github_json
    		user_json["owner"]["icon"] = icon_json if icon_json
    	end

    	user_json.to_json
	end

	def error_creating_tenant!
		self.eb_tenant_id = "error"
		self.does_not_require_password = true
		self.save!
	end

	def calculate_tenant_name!
		self.calculate_tenant_name
		self.does_not_require_password = true
		self.save!		
	end

	def calculate_tenant_name
		tenant_name = self.authentication.try(:github_username).try(:only_letters_and_numbers) || self.email.email_root.only_letters_and_numbers
		cnt = 0

		while Account.find_by_eb_tenant_name(tenant_name+cnt.to_s) do
			cnt += 1
			tenant_name = tenant_name + cnt.to_s
		end if Account.find_by_eb_tenant_name(tenant_name)

		self.eb_tenant_name = tenant_name
		self
	end





	protected
	def downcase_email
		self.email = self.email.downcase
	end


	def encrypt_password
		if self.password.present?
			self.encrypted_password = Digest::SHA1.hexdigest(self.password)
		end		
	end

	def first_name
		self.name.split(' ')[0]
	end

	def last_name
		self.name.split(' ')[1] || ""
	end



	private
	def has_valid_email?
		unless !self.email.blank? and self.email.is_valid_email?
			errors.add :email, "is not valid"
		end
	end


	def generate_token#_and_calculate_name
		self.token = Digest::SHA1.hexdigest([Time.now, rand].join)
		#self.name = self.authentication.try(:github_username) if self.name.blank?
	end


	def enqueue_tenant_creation
		options = {}
		options[:password] = self.try(:password)

		Resque.enqueue(CreateEBAccount, self.id, options)
	end


	def set_email_and_encrypt_password
		self.encrypt_password
		self.downcase_email
	end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  http_basic_authenticate_with name: APP_CONFIG['admin_username'], password: APP_CONFIG['admin_pwd'], only: ['index']
  layout "splash"

  def login
  end


  def signup
    @account ||= Account.new
#    @signup_callback_url = signup_callback_url
  end


  def create
    @account ||= Account.new(account_params)
    @account.password = account_params["password"]

    logger.debug "SIGNING UP >>>> #{@account.inspect}"
    logger.debug "SIGNING UP >>>> #{account_params.inspect}"
    logger.debug "SIGNING UP >>>> #{@account.password}"
    logger.debug "SIGNING UP >>>> #{params.inspect}"

    if @account.save
      respond_to do |format|
        format.html { render :processing }
      end

    else
      respond_to do |format|
        format.html { render :signup }
      end
    end
  end


  def processing
    @account = Account.find_by_token(params[:account_token])


    #cookies[:token] = { :value => value, :expires => 1.hour.from_now }


  end


  def index
    @accounts = Account.paginate(:page => params[:page])
    render layout: "application"
  end


  def check_status
  	# call the service and get status
    logger.debug ">>>>>>>>>>> CHECKING STATUS"
    @account = Account.find_by_token(params[:account_token])
    logger.debug ">>>>>>>>>>> CHECKING STATUS account: #{@account.inspect}"


    status = @account.check_tenant_status

    case status
    when 'processing'
      # do it again
      render json: { status: :processing }

#      respond_to do |format|
#        format.json { render json: { status: :processing}}
#      end

    when 'ready'
      response["Set-Cookie"] = "token=#{@account.eb_cookie}; Path=/;"
      @account.eb_cookie = nil
      @account.does_not_require_password = true
      @account.save

      render json: { status: :ok }
#      respond_to do |format|
#        format.json { render json: { status: :ok } }
#      end

    when 'error'
      # stop with error
      render json: { status: :error, message: "Something went wrong" }
#      respond_to do |format|
#        format.json { render json: { status: :error, message: "Something went wrong" }}
#      end

    end
  end


  private
  def account_params
    params.require(:account).permit(:name, :email, :password)
  end
end

app/views/accounts/index.haml
.container
  %h1{:style => "margin-top: 100px"} Accounts
  %table.table.table-striped
    %thead
      %tr
        %th Name
        %th Email
        %th Created At


    %tbody
      - @accounts.each do |a|
        %tr
          %th= a.name
          %th= a.email
          %th= a.created_at

    = will_paginate @accounts

app/views/accounts/login.haml
%script
  mixpanel.track("Login Page Rendered")

.login-window
  .login-inner
    .container
      .row
        .col-md-6.col-md-offset-3.text-center.splash-container
          .splash-logo
          .col-md-12.login-container

            %button.btn.btn-success.btn-block.signup{ style: "width:100%;" }
              .i.icon-github.icon-2x
              Log in with GitHub
            %br
            .hrule
              %span
                or
            %form{ "role" => "form" }

              .form-group
                %input{ :class => "form-control", :placeholder => "Email", "type" => "email" }

              .form-group
                %input{ :class => "form-control", :placeholder => "Password", "type" => "password" }

              .checkbox#checkbox-login.text-left
                %input{ :type => "checkbox" }
                = label_tag "Remember me"

              .text-right
                %button.btn.btn-warning#button-login
                  Log in

app/views/accounts/processing.haml
%script
  mixpanel.track("Processing Page Rendered")

.login-window
  .login-inner
    .container
      .row
        .col-md-6.col-md-offset-3.text-center.splash-container-processing
          .loading
            =image_tag 'logo_spin.png'
          .splash-logo-base
          .col-md-10.col-md-offset-1
            %h2.message Please wait while your account is being created!


#processing-account(data-account_token = "#{@account.token}" data-github_auth = "#{@account.authentication.present?}")

= link_to "Go to slingshot", "https://github.com/login/oauth/authorize?client_id=d11e2355450c1567c0bd"

app/views/accounts/signup.haml
%script
  mixpanel.track("Signup Page Rendered")

.login-window
  .login-inner
    .container
      .row
        .col-md-6.col-md-offset-3.text-center.splash-container
          .splash-logo
          .col-md-12.login-container
            = link_to "<i class='icon-github icon-2x'></i>Sign up with GitHub".html_safe, omniauth_signin_path('github'), :class => "btn btn-lg btn-block btn-success text-center signup", id: "github-signup"
            %br
            .hrule
              %span
                or
            = form_for @account, url: eb_path(create_account_path), method: :post do |f|
              - if @account.errors.any?
                #error_explanation.alert.alert-danger.text-left
                  %button.close{'type' => 'button', 'data-dismiss' => 'alert', href: '#', 'aria-hidden' => 'true'} x
                  %h4= "#{pluralize(@account.errors.count, "error")} prohibited this account from being saved:"
                  %ul
                    - @account.errors.full_messages.each do |msg|
                      %li.h5= msg

              .form-group
                = f.text_field :name, class: "form-control", placeholder: "Name"

              .form-group
                = f.text_field :email, class: "form-control", placeholder: "Email" #, type: "email"

              .form-group
                = f.text_field :password, class: "form-control", placeholder: "Password", type: "password"

              .checkbox#checkbox-login.text-left
                = check_box_tag :remember_me
                = label_tag "Remember me"

              .text-right
                = f.submit "Sign up", class: "button btn btn-warning", id: "splash-button-signup"